application:
    port: 8000
    host: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
    # reqwest::Url::parse throws error, if we provide just localhost
    base_url: "http://localhost"
    sender_email: "test@gmail.com"
    # We are only setting the development value, we'll deal with the production token outside of version control
    # (given that it's a sensitive secret!)
    authorization_token: "my-secret-token"
    timeout_milliseconds: 10000
